version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1

    working_directory: ~/repo

    steps:
      - checkout
  test:
      docker:
        - image: circleci/node:9.11.1
      
      steps:
        - run:
            name: Test
            command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          type: approval
      - test

